# ==========================================
# TradeLink Configuration
# ==========================================
# Choose your language. Available by default: en, de
# You can create your own language files in the /lang/ folder!
language: en